version: "3.4"

services:
  php:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./:/var/www
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    env_file:
      - .env.local

###> doctrine/doctrine-bundle ###
  database:
    image: mysql
#    container_name: db_docker_symfony
    restart: always
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
#      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
    - 8413:3306

  phpmyadmin:
    image: phpmyadmin
#    container_name: phpmyadmin_docker_symfony
    restart: always
    depends_on:
      - database
    ports:
      - 8088:80
    environment:
      PMA_HOST: database

  maildev:
    image: maildev/maildev
#    container_name: maildev_docker_symfony
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - 8081:80
    restart: always

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
